// source: recUnit.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_type_date_pb = require('./google/type/date_pb.js');
goog.object.extend(proto, google_type_date_pb);
goog.exportSymbol('proto.com.demo.webfluxdemo.recUnit.ListOfAny', null, global);
goog.exportSymbol('proto.com.demo.webfluxdemo.recUnit.RecFilter', null, global);
goog.exportSymbol('proto.com.demo.webfluxdemo.recUnit.RecUnit', null, global);
goog.exportSymbol('proto.com.demo.webfluxdemo.recUnit.RecUnitKey', null, global);
goog.exportSymbol('proto.com.demo.webfluxdemo.recUnit.RecUnitResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.demo.webfluxdemo.recUnit.RecUnitKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.demo.webfluxdemo.recUnit.RecUnitKey.displayName = 'proto.com.demo.webfluxdemo.recUnit.RecUnitKey';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.demo.webfluxdemo.recUnit.RecUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.demo.webfluxdemo.recUnit.RecUnit.displayName = 'proto.com.demo.webfluxdemo.recUnit.RecUnit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.repeatedFields_, null);
};
goog.inherits(proto.com.demo.webfluxdemo.recUnit.RecUnitResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.displayName = 'proto.com.demo.webfluxdemo.recUnit.RecUnitResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.demo.webfluxdemo.recUnit.ListOfAny.repeatedFields_, null);
};
goog.inherits(proto.com.demo.webfluxdemo.recUnit.ListOfAny, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.demo.webfluxdemo.recUnit.ListOfAny.displayName = 'proto.com.demo.webfluxdemo.recUnit.ListOfAny';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.demo.webfluxdemo.recUnit.RecFilter.repeatedFields_, null);
};
goog.inherits(proto.com.demo.webfluxdemo.recUnit.RecFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.demo.webfluxdemo.recUnit.RecFilter.displayName = 'proto.com.demo.webfluxdemo.recUnit.RecFilter';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.toObject = function(opt_includeInstance) {
  return proto.com.demo.webfluxdemo.recUnit.RecUnitKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    componentId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    recDate: (f = msg.getRecDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    workUnitId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    recStatus: jspb.Message.getFieldWithDefault(msg, 5, 0),
    grainId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    grainMap: (f = msg.getGrainMap()) ? f.toObject(includeInstance, proto.google.protobuf.Any.toObject) : [],
    recTypeFamily: jspb.Message.getFieldWithDefault(msg, 8, 0),
    workUnitTypeId: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.demo.webfluxdemo.recUnit.RecUnitKey;
  return proto.com.demo.webfluxdemo.recUnit.RecUnitKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setComponentId(value);
      break;
    case 3:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setRecDate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWorkUnitId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRecStatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGrainId(value);
      break;
    case 7:
      var value = msg.getGrainMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Any.deserializeBinaryFromReader, "", new proto.google.protobuf.Any());
         });
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRecTypeFamily(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWorkUnitTypeId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.demo.webfluxdemo.recUnit.RecUnitKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getComponentId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getRecDate();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getWorkUnitId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getRecStatus();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getGrainId();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getGrainMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Any.serializeBinaryToWriter);
  }
  f = message.getRecTypeFamily();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getWorkUnitTypeId();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
};


/**
 * optional string key_id = 1;
 * @return {string}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 component_id = 2;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getComponentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setComponentId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.type.Date rec_date = 3;
 * @return {?proto.google.type.Date}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getRecDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 3));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setRecDate = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.clearRecDate = function() {
  return this.setRecDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.hasRecDate = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 work_unit_id = 4;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getWorkUnitId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setWorkUnitId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 rec_status = 5;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getRecStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setRecStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 grain_id = 6;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getGrainId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setGrainId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * map<string, google.protobuf.Any> grain = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Any>}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getGrainMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Any>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.google.protobuf.Any));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.clearGrainMap = function() {
  this.getGrainMap().clear();
  return this;};


/**
 * optional int32 rec_type_family = 8;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getRecTypeFamily = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setRecTypeFamily = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 work_unit_type_id = 9;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.getWorkUnitTypeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitKey} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitKey.prototype.setWorkUnitTypeId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.com.demo.webfluxdemo.recUnit.RecUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: (f = msg.getKey()) && proto.com.demo.webfluxdemo.recUnit.RecUnitKey.toObject(includeInstance, f),
    metaDataMap: (f = msg.getMetaDataMap()) ? f.toObject(includeInstance, proto.google.protobuf.Any.toObject) : [],
    searchableFieldsMap: (f = msg.getSearchableFieldsMap()) ? f.toObject(includeInstance, proto.google.protobuf.Any.toObject) : [],
    knowledgeBegin: (f = msg.getKnowledgeBegin()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    knowledgeEnd: (f = msg.getKnowledgeEnd()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.demo.webfluxdemo.recUnit.RecUnit;
  return proto.com.demo.webfluxdemo.recUnit.RecUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.demo.webfluxdemo.recUnit.RecUnitKey;
      reader.readMessage(value,proto.com.demo.webfluxdemo.recUnit.RecUnitKey.deserializeBinaryFromReader);
      msg.setKey(value);
      break;
    case 2:
      var value = msg.getMetaDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Any.deserializeBinaryFromReader, "", new proto.google.protobuf.Any());
         });
      break;
    case 3:
      var value = msg.getSearchableFieldsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Any.deserializeBinaryFromReader, "", new proto.google.protobuf.Any());
         });
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setKnowledgeBegin(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setKnowledgeEnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.demo.webfluxdemo.recUnit.RecUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.demo.webfluxdemo.recUnit.RecUnitKey.serializeBinaryToWriter
    );
  }
  f = message.getMetaDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Any.serializeBinaryToWriter);
  }
  f = message.getSearchableFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Any.serializeBinaryToWriter);
  }
  f = message.getKnowledgeBegin();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getKnowledgeEnd();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional RecUnitKey key = 1;
 * @return {?proto.com.demo.webfluxdemo.recUnit.RecUnitKey}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.getKey = function() {
  return /** @type{?proto.com.demo.webfluxdemo.recUnit.RecUnitKey} */ (
    jspb.Message.getWrapperField(this, proto.com.demo.webfluxdemo.recUnit.RecUnitKey, 1));
};


/**
 * @param {?proto.com.demo.webfluxdemo.recUnit.RecUnitKey|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.setKey = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.clearKey = function() {
  return this.setKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.hasKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<string, google.protobuf.Any> meta_data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Any>}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.getMetaDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Any>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.google.protobuf.Any));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.clearMetaDataMap = function() {
  this.getMetaDataMap().clear();
  return this;};


/**
 * map<string, google.protobuf.Any> searchable_fields = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Any>}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.getSearchableFieldsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Any>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.google.protobuf.Any));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.clearSearchableFieldsMap = function() {
  this.getSearchableFieldsMap().clear();
  return this;};


/**
 * optional google.protobuf.Timestamp knowledge_begin = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.getKnowledgeBegin = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.setKnowledgeBegin = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.clearKnowledgeBegin = function() {
  return this.setKnowledgeBegin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.hasKnowledgeBegin = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp knowledge_end = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.getKnowledgeEnd = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.setKnowledgeEnd = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.clearKnowledgeEnd = function() {
  return this.setKnowledgeEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnit.prototype.hasKnowledgeEnd = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    recUnitsList: jspb.Message.toObjectList(msg.getRecUnitsList(),
    proto.com.demo.webfluxdemo.recUnit.RecUnit.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.demo.webfluxdemo.recUnit.RecUnitResponse;
  return proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.demo.webfluxdemo.recUnit.RecUnit;
      reader.readMessage(value,proto.com.demo.webfluxdemo.recUnit.RecUnit.deserializeBinaryFromReader);
      msg.addRecUnits(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecUnitsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.demo.webfluxdemo.recUnit.RecUnit.serializeBinaryToWriter
    );
  }
};


/**
 * repeated RecUnit rec_units = 1;
 * @return {!Array<!proto.com.demo.webfluxdemo.recUnit.RecUnit>}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.getRecUnitsList = function() {
  return /** @type{!Array<!proto.com.demo.webfluxdemo.recUnit.RecUnit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.demo.webfluxdemo.recUnit.RecUnit, 1));
};


/**
 * @param {!Array<!proto.com.demo.webfluxdemo.recUnit.RecUnit>} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.setRecUnitsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecUnit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnit}
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.addRecUnits = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.demo.webfluxdemo.recUnit.RecUnit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecUnitResponse} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecUnitResponse.prototype.clearRecUnitsList = function() {
  return this.setRecUnitsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.toObject = function(opt_includeInstance) {
  return proto.com.demo.webfluxdemo.recUnit.ListOfAny.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.demo.webfluxdemo.recUnit.ListOfAny} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldList: jspb.Message.toObjectList(msg.getFieldList(),
    google_protobuf_any_pb.Any.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.demo.webfluxdemo.recUnit.ListOfAny}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.demo.webfluxdemo.recUnit.ListOfAny;
  return proto.com.demo.webfluxdemo.recUnit.ListOfAny.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.demo.webfluxdemo.recUnit.ListOfAny} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.demo.webfluxdemo.recUnit.ListOfAny}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.addField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.demo.webfluxdemo.recUnit.ListOfAny.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.demo.webfluxdemo.recUnit.ListOfAny} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * repeated google.protobuf.Any field = 1;
 * @return {!Array<!proto.google.protobuf.Any>}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.getFieldList = function() {
  return /** @type{!Array<!proto.google.protobuf.Any>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_any_pb.Any, 1));
};


/**
 * @param {!Array<!proto.google.protobuf.Any>} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.ListOfAny} returns this
*/
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.setFieldList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.protobuf.Any=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Any}
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.addField = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.protobuf.Any, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.ListOfAny} returns this
 */
proto.com.demo.webfluxdemo.recUnit.ListOfAny.prototype.clearFieldList = function() {
  return this.setFieldList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.repeatedFields_ = [4,7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.com.demo.webfluxdemo.recUnit.RecFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
    recDate: (f = msg.getRecDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    recTypeFamilyId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    asOfTime: (f = msg.getAsOfTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    workUnitIdsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    searchFieldsMap: (f = msg.getSearchFieldsMap()) ? f.toObject(includeInstance, proto.com.demo.webfluxdemo.recUnit.ListOfAny.toObject) : [],
    grainFieldsMap: (f = msg.getGrainFieldsMap()) ? f.toObject(includeInstance, proto.com.demo.webfluxdemo.recUnit.ListOfAny.toObject) : [],
    recStatusIdsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    componentIdsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.demo.webfluxdemo.recUnit.RecFilter;
  return proto.com.demo.webfluxdemo.recUnit.RecFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setRecDate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRecTypeFamilyId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setAsOfTime(value);
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addWorkUnitIds(values[i]);
      }
      break;
    case 5:
      var value = msg.getSearchFieldsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.demo.webfluxdemo.recUnit.ListOfAny.deserializeBinaryFromReader, "", new proto.com.demo.webfluxdemo.recUnit.ListOfAny());
         });
      break;
    case 6:
      var value = msg.getGrainFieldsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.demo.webfluxdemo.recUnit.ListOfAny.deserializeBinaryFromReader, "", new proto.com.demo.webfluxdemo.recUnit.ListOfAny());
         });
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRecStatusIds(values[i]);
      }
      break;
    case 8:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addComponentIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.demo.webfluxdemo.recUnit.RecFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.demo.webfluxdemo.recUnit.RecFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getRecTypeFamilyId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAsOfTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getWorkUnitIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getSearchFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.demo.webfluxdemo.recUnit.ListOfAny.serializeBinaryToWriter);
  }
  f = message.getGrainFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.demo.webfluxdemo.recUnit.ListOfAny.serializeBinaryToWriter);
  }
  f = message.getRecStatusIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      7,
      f
    );
  }
  f = message.getComponentIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      8,
      f
    );
  }
};


/**
 * optional google.type.Date rec_date = 1;
 * @return {?proto.google.type.Date}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getRecDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 1));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setRecDate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearRecDate = function() {
  return this.setRecDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.hasRecDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 rec_type_family_id = 2;
 * @return {number}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getRecTypeFamilyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setRecTypeFamilyId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp as_of_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getAsOfTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
*/
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setAsOfTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearAsOfTime = function() {
  return this.setAsOfTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.hasAsOfTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated int32 work_unit_ids = 4;
 * @return {!Array<number>}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getWorkUnitIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setWorkUnitIdsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.addWorkUnitIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearWorkUnitIdsList = function() {
  return this.setWorkUnitIdsList([]);
};


/**
 * map<string, ListOfAny> search_fields = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.demo.webfluxdemo.recUnit.ListOfAny>}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getSearchFieldsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.demo.webfluxdemo.recUnit.ListOfAny>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.com.demo.webfluxdemo.recUnit.ListOfAny));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearSearchFieldsMap = function() {
  this.getSearchFieldsMap().clear();
  return this;};


/**
 * map<string, ListOfAny> grain_fields = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.demo.webfluxdemo.recUnit.ListOfAny>}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getGrainFieldsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.demo.webfluxdemo.recUnit.ListOfAny>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      proto.com.demo.webfluxdemo.recUnit.ListOfAny));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearGrainFieldsMap = function() {
  this.getGrainFieldsMap().clear();
  return this;};


/**
 * repeated int32 rec_status_ids = 7;
 * @return {!Array<number>}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getRecStatusIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setRecStatusIdsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.addRecStatusIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearRecStatusIdsList = function() {
  return this.setRecStatusIdsList([]);
};


/**
 * repeated int32 component_ids = 8;
 * @return {!Array<number>}
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.getComponentIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.setComponentIdsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.addComponentIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.demo.webfluxdemo.recUnit.RecFilter} returns this
 */
proto.com.demo.webfluxdemo.recUnit.RecFilter.prototype.clearComponentIdsList = function() {
  return this.setComponentIdsList([]);
};


goog.object.extend(exports, proto.com.demo.webfluxdemo.recUnit);
